apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        implement1/automatic-ecommerce: true
        implement1/cluster: true
        implement1/javaapp: true
        implement1/kolas: true
        implement1/sampleapp: true
        implement1/spring: true
        implement1/testrepo: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        implement1/automatic-ecommerce: merge
        implement1/cluster: merge
        implement1/javaapp: merge
        implement1/kolas: merge
        implement1/sampleapp: merge
        implement1/spring: merge
        implement1/testrepo: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - implement1/cluster
        - implement1/automatic-ecommerce
        - implement1/javaapp
        - implement1/kolas
        - implement1/sampleapp
        - implement1/spring
        - implement1/testrepo
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - implement1/cluster
        - implement1/automatic-ecommerce
        - implement1/javaapp
        - implement1/kolas
        - implement1/sampleapp
        - implement1/spring
        - implement1/testrepo
      target_url: http://lighthouse-jx.212-2-243-73.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
