apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: implement1
    provider: github
    repository: testrepo
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: implement1-testrepo
  namespace: jx
spec:
  httpCloneURL: https://github.com/implement1/testrepo.git
  org: implement1
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testrepo
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/implement1/testrepo
