apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: implement1
    provider: github
    repository: budget
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: implement1-budget
  namespace: jx
spec:
  httpCloneURL: https://github.com/implement1/budget.git
  org: implement1
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: budget
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/implement1/budget
