apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: implement1
    provider: github
    repository: demo-app
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: implement1-demo-app
  namespace: jx
spec:
  httpCloneURL: https://github.com/implement1/demo-app.git
  org: implement1
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: demo-app
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/implement1/demo-app
